
name: CI - API Tests
on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 8080:80
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Wait for services
        run: |
          ./scripts/wait-for-service.sh localhost:8080
          ./scripts/wait-for-service.sh localhost:5672
      - name: Run pytest (Allure)
        run: |
          pytest -q --alluredir=allure-results
      - name: Upload Allure result
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

