name: Python API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Run pytest with Allure + HTML reports
      - name: Run tests
        run: |
          pytest --alluredir=reports/allure --html=reports/report.html

      # 5️⃣ Install Allure CLI to generate HTML report (optional, for interactive Allure UI)
      - name: Install Allure CLI
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt update
          sudo apt install allure -y

      # 6️⃣ Generate Allure HTML report
      - name: Generate Allure HTML report
        run: |
          allure generate reports/allure -o reports/allure-report --clean

      # 7️⃣ Upload Allure raw results as artifact
      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: reports/allure

      # 8️⃣ Upload Allure HTML report as artifact
      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v3
        with:
          name: allure-html-report
          path: reports/allure-report

      # 9️⃣ Upload pytest HTML report as artifact
      - name: Upload pytest HTML report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-html-report
          path: reports/report.html
