httpbin:
  base_url: "https://httpbin.org"

rabbitmq:
  host: "rabbitmq"    # default: works when inside docker
  port: 5672
  username: "guest"
  password: "guest"
  queue: "httpbin_test_queue"

metrics:
  enabled: true
  port: 8000

retry:
  max_attempts: 3
  backoff_seconds: 1

reporting:
  allure_results_dir: "./allure-results"
