
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'pytest_metrics'
    static_configs:
      - targets: ['metrics_exporter:8000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

